#!/usr/bin/env sh
#
#   dent-share - functions related to dent's host/container shared dirs
#
#   The _dent share_ is a directory shared between the host and a dent
#   container, used to pass files, sockets, etc. between them. (It is
#   normally bind-mounted at the same path in both.) It lives at
#   $XDG_STATE_HOME/dent/<container>, with, per the XDG spec,
#   $XDG_STATE_HOME defaulting to $HOME/.local/state. Note that once the
#   container is created neither the host nor the container path may
#   change, so you should not change $XDG_STATE_HOME in either.
#
#   See usage() for usage.
set -eu

####################################################################
#   Utility functions

####################################################################
#   Commands

command_dir() {
    local container=${1:-${DENT_CONTAINER:-}}
    if [ -n "$container" ]; then
        printf '%s\n' "$state/dent/$container"
    else
        printf '%s\n' "$state/dent"
    fi
}

command_cat_entry_script() {
    local esfname="${1:-}"; shift
    local dir=$(command_dir '')
    cat "$dir/entry-script/$esfname" 2>/dev/null || true
}

####################################################################

usage() {
    cat <<_____
Usage: $progname COMMAND [ARGS]

Commands:

* dir [CONTAINER]: Print _container_'s share dir
  - With CONTAINER, print that container's share dir.
  - Else if \$DENT_CONTAINER is set (as it is inside a dent container),
    print that container's share dir.
  - Else print the base dir holding every container's share.

* cat-entry-script SCRIPTNAME: Print the entry script SCRIPTNAME (typically
  something like 'startup.20260720T123922.58937'. If not found (i.e., the
  dent share isn't working properly), print nothing. This is intended to be
  'eval'd by the code that executes the entry.

_____
}

progname="$(basename "$0")"
state=${XDG_STATE_HOME:-$HOME/.local/state}

case "${1:-}" in
    he*)                usage;;
    dir)                shift; command_dir "$@";;
    cat-entry-script)   shift; command_cat_entry_script "$@";;
    *) echo 1>&2 "$progname: bad command; try 'help' for usage"; exit 2;;
esac
