#!/usr/bin/env bash
set -e -o pipefail

die() { echo 1>&2 "$(basename "$0"):" "$@"; exit 1; }

base=$(cd "$(dirname "$0")" && pwd -P)
cd $base
sudo -v || die 'Cannot sudo to run docker'
docker='sudo docker'

image=capps-bind:latest
port=53
dockerargs=()
while true; do case "$1" in
    -T)     #   Test mode; you may want to add --detach=false
            shift; image=capps-bind:test; port=1053
            ;;
    --)     shift; break;;              # named args follow
    '')     break;;
    *)      dockerargs+=($1); shift;;
esac; done

#   XXX Always using --rm means we need to move logs outside container.
$docker run --rm --detach=true \
    -p $port:53 -p $port:53/udp \
    "${dockerargs[@]}" $image "$@"
